### ISSUE TITLE
Please explain plugin uniqueness

### ISSUE THREAD

**Issue by pcav** [kradziko/geo4work_wtyczka#2]
The functionality described in the About seems already present in several other QGIS plugins.
Please clarify what the plugin is actually adding, and consider joining forces with other plugin devs. See a recent similar discussion on the bugtracker of a similar plugin.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by kradziko** [comment]
The Quick Layout plugin allows to quick prepare map print from current QGIS view. Using maximum 7 clicks user can add several functions to print layout such as title, scale (numerical scale or graphic scale), North arrow and legend. At the end user can save layout as pdf or png. In our opinion what distinguishes us is legend function and two ways of presentation scale function.

**Comment by pcav** [comment]
Thanks. Are you sure other plugins are very different from that? Could you please consider merging your work with one of the existing ones?
Cheers.

**Comment by kradziko** [comment]
We are quite sure that legend function is unique in our plugin in QGIS 2 what makes it very useful - I am convinced that maps without legend function sometimes can be unclear even if it is a quick printing. We don't want merging our work with one of the existing one because in our opinion our plugin contains all funcions from others plugin and much more. We care a lot to publish our plugin because it is prestige for us and we'd be glad if we could take part in the process of creating the QGIS plugins repository.

**Comment by pcav** [comment]
Thanks for your reply. I understand it is a nice feeling being the sole author of something, but joining forces is the key of Free and Open Source Software success. Let me therefore insist to start a public discussion to merge all printing plugins into one compete and shared.
Thanks.

**Comment by pcav** [comment]
Moreover, QGIS2 is end of life and unsupported, so publishing a 2.0 only plugin is inappropriate.

**Comment by kradziko** [comment]
I understand, thank you for the answer and the whole discussion.

**Comment by pcav** [comment]
The ticket is still valid, please do not close it.
Thanks.
